[build]
  base = "."
  command = "npm run dev"
  publish = "dist/public"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "dist/public"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
